'use client'

import { useState } from 'react'

type Floor = { number: string; label: string; title: string; intro: string; bullets: string[]; decision: string; impact: string; question: string; diagram: string; composition?: string; metrics?: string[] }

const floors: Floor[] = [
  { number: '00', label: 'FUNDAÇÃO', title: 'Antes de subir, desenhe o terreno', intro: 'Microfrontends não começam com um framework. Começam com uma decisão: dividir o produto em domínios que equipes conseguem entender, entregar e evoluir de forma independente.', bullets: ['Monólito: um canteiro, uma release, uma mudança pode atravessar o prédio inteiro.', 'MFE: uma composição de aplicações menores dentro de uma experiência única.', 'Independência não é isolamento absoluto: é autonomia com contratos.'], decision: 'Mapear domínios de negócio antes de mapear componentes.', impact: 'Mais autonomia para times; mais responsabilidade por integração.', question: 'Qual parte do seu produto poderia ser reformada sem interditar o prédio?', diagram: 'foundation' },
  { number: '01', label: 'ANDAR 1 · LIMITES', title: 'A complexidade sobe pelas escadas', intro: 'A limitação central é mental. Conforme o sistema cresce, mudanças amplificam, a carga cognitiva aumenta e surgem desconhecidos que ninguém consegue enxergar completamente.', bullets: ['Amplificação: uma alteração em checkout exige tocar navegação, estado e design system.', 'Carga cognitiva: cada pessoa precisa conhecer corredores demais.', 'Desconhecidos: dependências implícitas aparecem apenas em produção.'], decision: 'Criar fronteiras que reduzam o número de coisas que cada time precisa manter na cabeça.', impact: 'Menos raio de explosão; mais superfícies de integração para governar.', question: 'Quantos cômodos você consegue manter na cabeça antes de começar a esquecer as conexões?', diagram: 'complexity' },
  { number: '02', label: 'ANDAR 2 · DOMÍNIOS', title: 'Paredes claras, portas públicas', intro: 'Um domínio encapsula sua complexidade e expõe apenas uma API pública. O design é iterativo: as paredes melhoram conforme aprendemos onde o negócio realmente muda.', bullets: ['Cada MFE acompanha um domínio, uma equipe e um ciclo de deploy.', 'APIs públicas estáveis protegem consumidores da reforma interna.', 'Shared UI e tokens são fundação compartilhada, não atalhos para acessar internals.'], decision: 'Definir ownership, contrato e responsabilidade operacional de cada fatia.', impact: 'O deploy se torna independente; a governança de contratos vira essencial.', question: 'Onde você colocaria a parede entre Catálogo, Checkout e Conta?', diagram: 'domains' },
  { number: '03', label: 'ANDAR 3 · MODULE FEDERATION', title: 'Module Federation: guindaste compartilhado', intro: 'O host carrega módulos remotos em runtime. Webpack ou Rspack podem compartilhar React, design system e outras dependências, evitando duplicação e acelerando a composição.', bullets: ['Remotes publicados independentemente e consumidos pelo shell.', 'shared permite singleton e controle de versões de dependências críticas.', 'Excelente quando os times compartilham ecossistema, tooling e runtime.'], decision: 'Definir quem é host, quais remotes existem e quais dependências podem ser shared.', impact: 'Boa performance e DX; risco de acoplamento de versão e falhas em runtime.', question: 'Quais dependências podem ser uma fundação comum sem virar um pilar único de falha?', diagram: 'federation' },
  { number: '04', label: 'ANDAR 4 · NATIVE FEDERATION', title: 'Native Federation: módulos com ESM nativo', intro: 'Native Federation leva a ideia para os padrões do navegador: ES Modules, import maps e manifests. A obra depende menos de um bundler específico e se aproxima da plataforma web.', bullets: ['Import maps resolvem de onde vem cada módulo.', 'ESM preserva padrões nativos e favorece interoperabilidade entre toolchains.', 'Exige disciplina de browser support, pré-carregamento, versionamento e observabilidade.'], decision: 'Escolher entre conveniência do bundler e portabilidade baseada na plataforma.', impact: 'Menor lock-in de ferramenta; mais decisões explícitas sobre distribuição e cache.', question: 'Você quer que a planta dependa do guindaste ou que o próprio navegador saiba montar os módulos?', diagram: 'native' },
  { number: '05', label: 'ANDAR 5 · WEB COMPONENTS', title: 'Web Components: cômodos agnósticos', intro: 'Custom Elements e Shadow DOM oferecem um contrato baseado na plataforma. Um componente pode ser usado por React, Angular, Vue ou HTML puro sem compartilhar o runtime do framework.', bullets: ['Shadow DOM encapsula estilos e reduz vazamento visual.', 'Custom events e propriedades formam uma API explícita.', 'Mais isolamento e longevidade; integração, SSR e duplicação de runtime exigem cuidado.'], decision: 'Usar a plataforma como fronteira quando autonomia tecnológica vale mais que ergonomia.', impact: 'Portabilidade e isolamento; mais trabalho de acessibilidade, tipagem e composição.', question: 'Este cômodo precisa funcionar em qualquer prédio ou apenas neste ecossistema?', diagram: 'webcomponents' },
  { number: '06', label: 'ANDAR 6 · IDENTIDADE', title: 'Autenticação: uma portaria, não oito catracas', intro: 'Identidade é uma preocupação transversal. O usuário deve autenticar uma vez; os MFEs não devem duplicar login, guardar tokens em lugares inseguros ou criar sessões concorrentes.', bullets: ['O shell ou um BFF coordena sessão baseada em cookie seguro e HttpOnly.', 'MFEs recebem contexto mínimo: usuário, permissões e estado de sessão.', 'Autorização acontece no backend por domínio; esconder botão não é controle de acesso.', 'Logout, expiração, renovação e cross-origin precisam de contrato operacional claro.'], decision: 'Centralizar autenticação; descentralizar autorização e políticas do domínio.', impact: 'Experiência consistente e menor superfície de ataque; exige alinhamento de claims, CORS e cookies.', question: 'Quem controla a chave da portaria — e como cada andar prova que o visitante pode entrar?', diagram: 'auth' },
  { number: '07', label: 'ANDAR 7 · INFRAESTRUTURA', title: 'A portaria esconde os corredores', intro: 'O Reverse Proxy recebe a requisição e encaminha para shell, MFE ou BFF. Com HATEOAS, o backend também sinaliza próximos recursos e ações sem expor o mapa interno.', bullets: ['Proxy reverso roteia por domínio, path ou versão sem o usuário conhecer topologia.', 'BFF adapta dados e reduz chamadas acopladas do browser.', 'Links HATEOAS funcionam como placas: ações disponíveis, próximos recursos e rotas.', 'Observabilidade precisa seguir a jornada entre portaria, corredores e andares.'], decision: 'Manter o frontend guiado por contratos e capacidades, não por endereços internos.', impact: 'Topologia substituível; exige links consistentes, tracing e fallback de versões.', question: 'Se um andar mudar de endereço amanhã, o visitante perceberá ou apenas seguirá a próxima placa?', diagram: 'gateway' },
  { number: '08', label: 'ANDAR 8 · REUSO', title: 'Reusar não é copiar paredes', intro: 'Reuso reduz trabalho quando existe uma linguagem comum, mas cria dependências quando é feito sem critério. A pergunta não é “posso compartilhar?”, e sim “quem controla a evolução deste contrato?”.', bullets: ['Reuse tokens, componentes acessíveis e padrões estáveis — não regras de negócio internas.', 'Prefira APIs pequenas, versionadas e documentadas; evite um shared gigantesco.', 'Um componente só é realmente reutilizável quando tem semântica, teclado, responsividade e testes próprios.', 'Cuidado com acoplamento: reuso excessivo transforma a fundação em gargalo para todos os andares.'], decision: 'Compartilhar capacidades maduras; manter decisões de domínio próximas de quem as possui.', impact: 'Menos duplicação e UX consistente; mais governança, versionamento e risco de dependência.', question: 'Este componente é uma peça padrão ou uma parede que só parece igual?', diagram: 'reuse', composition: 'design system · contratos versionados' },
]

function Diagram({ kind }: { kind: string }) {
  if (kind === 'foundation') return <div className="diagram tower"><div className="tower-roof">PRODUTO DIGITAL</div><div className="tower-floor">CATÁLOGO <small>domínio</small></div><div className="tower-floor">CHECKOUT <small>domínio</small></div><div className="tower-floor">CONTA <small>domínio</small></div><div className="ground">FUNDAÇÃO · CONTRATOS · OBSERVABILIDADE</div></div>
  if (kind === 'complexity') return <div className="diagram complexity"><div className="core">SISTEMA<br/><strong>?</strong></div><i className="orbit o1">mudanças</i><i className="orbit o2">dependências</i><i className="orbit o3">desconhecidos</i><span className="annotation">cada reforma<br/>aumenta o raio</span></div>
  if (kind === 'domains') return <div className="diagram domain-grid">{['CATÁLOGO','CHECKOUT','CONTA'].map((x) => <div className="domain-room" key={x}><b>{x}</b><small>API pública</small><span>□</span></div>)}<em>paredes claras / portas estáveis</em></div>
  if (kind === 'federation') return <div className="diagram federation"><div className="host">HOST / SHELL</div><div className="beam">runtime · shared</div><div className="remotes"><span>REMOTE A</span><span>REMOTE B</span><span>REMOTE C</span></div><small>dependências compartilhadas</small></div>
  if (kind === 'native') return <div className="diagram native"><div className="manifest">MANIFEST.JSON</div><div className="import-line">import map →</div><div className="esm"><b>ESM</b><span>navegador</span></div><div className="native-modules"><i>módulo A</i><i>módulo B</i><i>módulo C</i></div></div>
  if (kind === 'webcomponents') return <div className="diagram webc"><div className="shadow"><b>&lt;checkout-card&gt;</b><small>SHADOW DOM</small></div><div className="events">props ↓ &nbsp;&nbsp; events ↑</div><div className="frameworks"><span>React</span><span>Vue</span><span>HTML</span></div></div>
  if (kind === 'auth') return <div className="diagram auth"><div className="identity">IDENTITY<br/><small>cookie HttpOnly</small></div><div className="auth-gate">PORTARIA<br/><b>SSO</b></div><div className="auth-floors"><span>shell</span><span>checkout</span><span>conta</span></div><div className="shield">AUTHN ≠ AUTHZ</div></div>
  if (kind === 'reuse') return <div className="diagram reuse"><div className="token-kit"><b>DESIGN SYSTEM</b><span>tokens</span><span>componentes</span><span>acessibilidade</span></div><div className="reuse-arrows">↙ &nbsp; ↓ &nbsp; ↘</div><div className="reuse-domains"><i>Catálogo</i><i>Checkout</i><i>Conta</i></div><small>contrato versionado · ownership claro</small></div>
  return <div className="diagram gateway"><div className="proxy">REVERSE<br/>PROXY</div><div className="route">requisição →</div><div className="service-stack"><span>SHELL</span><span>BFF</span><span>MFE</span></div><div className="hateoas">→ ação disponível<br/>→ próximo recurso</div></div>
}

export default function Page() {
  const [current, setCurrent] = useState(0)
  const floor = floors[current]
  return <main className="workshop-shell"><header className="topbar"><div className="brand-mark">MFE<span>／</span>LAB</div><div className="session-label">WORKSHOP DE ARQUITETURA <span>● AO VIVO</span></div><div className="step-count">{floor.number} <span>/ 08</span></div></header><div className="layout"><nav className="floor-nav" aria-label="Andares do workshop"><p>PLANTA VERTICAL</p>{floors.map((item, index) => <button key={item.number} className={index === current ? 'selected' : ''} onClick={() => setCurrent(index)}><span>{item.number}</span>{item.label}</button>)}</nav><section className="content-grid"><article className="narrative"><p className="eyebrow">{floor.label}</p><h1>{floor.title}</h1><p className="lead">{floor.intro}</p><ul>{floor.bullets.map((b) => <li key={b}>{b}</li>)}</ul><div className="decision"><span>DECISÃO DE PROJETO</span><p>{floor.decision}</p><small>IMPACTO · {floor.impact}</small></div><div className="impact-strip" aria-label="Impacto percebido pelo usuário"><span><b>CARREGAMENTO</b><strong>{floor.number === '03' ? 'runtime' : floor.number === '05' ? 'isolado' : 'progressivo'}</strong></span><span><b>MOBILE</b><strong>{floor.number === '03' ? 'shared' : 'menos JS'}</strong></span><span><b>RISCO</b><strong>{floor.number === '05' ? 'estilos' : 'contrato'}</strong></span></div><div className="composition-note"><span>COMPOSIÇÃO</span><b>{floor.composition ?? (current < 3 ? 'build-time · shell único' : 'runtime · módulos sob demanda')}</b></div><div className="question"><span>PAUSA PARA A SALA</span><p>{floor.question}</p></div><div className="nav-actions"><button className="back" disabled={current === 0} onClick={() => setCurrent(Math.max(0, current - 1))}>← voltar</button><button className="next" onClick={() => setCurrent(current === floors.length - 1 ? 0 : current + 1)}>{current === floors.length - 1 ? 'descer ao térreo' : 'subir um andar'} <span>↑</span></button></div></article><aside className="blueprint-panel"><div className="panel-top"><span>PLANTA / {floor.number}</span><span>ESCALA 1:100</span></div><div className="building-progress" aria-label={`Prédio com ${current + 1} andares construídos`}><div className="building-roof">MFE TOWER</div>{floors.slice(0, current + 1).map((item) => <div className="built-floor" key={item.number}><span>{item.number}</span><b>{item.label.split(' · ')[0]}</b><i>✓</i></div>)}<div className="building-foundation">ALICERCE · CONTRATOS · OBSERVABILIDADE</div></div><Diagram kind={floor.diagram} /><div className="panel-caption"><span>rascunho de arquitetura</span><span>decisão antes do componente</span></div></aside></section></div><footer className="footer-note"><span>ARQUITETURA EVOLUTIVA</span><span>cada andar reduz o que precisamos saber sobre os outros</span></footer></main>
}
