'use client'

import { useState } from 'react'

type Floor = { number: string; label: string; title: string; intro: string; bullets: string[]; example: string; impact: string; question: string; diagram: string }

const floors: Floor[] = [
  { number:'00', label:'TERRENO · O QUE É MFE', title:'Uma aplicação. Vários prédios.', intro:'Microfrontends dividem uma experiência frontend por domínios de negócio, permitindo que times entreguem partes independentes sem transformar o produto em um conjunto de ilhas.', bullets:['Independência de deploy não significa ausência de contratos.','Comece pelo domínio e ownership, não pelo framework.','O shell coordena a experiência; cada MFE controla sua capacidade.'], example:'Angular 21: shell de Loja + MFEs de Catálogo, Checkout e Conta.', impact:'Reduz raio de mudança, mas adiciona integração, observabilidade e governança.', question:'Qual domínio poderia ser reformado sem interditar o prédio?', diagram:'tower' },
  { number:'01', label:'ANDAR 1 · COMPOSIÇÃO', title:'Escolha quando a obra acontece', intro:'A composição pode acontecer antes do deploy, no servidor/edge ou no navegador. Essa escolha define cache, falhas, velocidade e independência.', bullets:['Build-time: simples e previsível, porém releases acopladas.','Server-side/edge: entrega HTML composto, bom para SSR e controle de rota.','Runtime: deploy independente, mas com risco de falha e latência remota.'], example:'Angular SSR pode compor fragmentos no edge; o browser recebe uma página já montada.', impact:'Quanto mais tarde compõe, maior a autonomia — e maior a responsabilidade operacional.', question:'Você aceita uma chamada extra para ganhar autonomia de deploy?', diagram:'composition' },
  { number:'02', label:'ANDAR 2 · FRONTEIRAS', title:'Paredes por domínio, não por componente', intro:'Fronteiras boas escondem decisões internas e expõem capacidades. Um MFE não deve conhecer o componente, store ou rota privada de outro.', bullets:['API pública pequena, sem internals vazados.','Ownership, versionamento e fallback explícitos.','Evite dividir um fluxo que sempre muda junto.'], example:'Checkout expõe “iniciar pagamento”; não expõe sua árvore de componentes.', impact:'Menos acoplamento e blast radius; mais disciplina de contratos.', question:'Onde está a porta pública de cada domínio?', diagram:'domains' },
  { number:'03', label:'ANDAR 3 · MODULE FEDERATION', title:'Module Federation: o host monta remotes', intro:'Webpack/Rspack carregam módulos remotos em runtime. É forte quando os times compartilham ecossistema e precisam compartilhar dependências.', bullets:['Host define o shell; remote publica entrypoint e módulos.','shared pode evitar Angular duplicado, mas singleton exige compatibilidade.','Manifest, versionamento e fallback são parte da arquitetura.'], example:'Angular 21: host carrega `checkout/Module` via `loadRemoteModule` e lazy route.', impact:'Runtime independente e bons chunks; risco de incompatibilidade, requests extras e remote indisponível.', question:'Quais dependências serão vigas compartilhadas — e quais devem permanecer locais?', diagram:'mf' },
  { number:'04', label:'ANDAR 4 · NATIVE FEDERATION', title:'Native Federation: o navegador entende a planta', intro:'Native Federation usa ESM, manifests e import maps, reduzindo dependência de um bundler específico e aproximando a composição da plataforma web.', bullets:['ESM permite módulos distribuídos como recursos web.','Import maps resolvem versões e origens.','Preload, cache e browser support precisam ser planejados.'], example:'Angular 21 + Native Federation: `initFederation()` lê manifest e `loadRemoteModule({remoteName, exposedModule})`.', impact:'Mais portabilidade e cache explícito; mais decisões sobre distribuição e compatibilidade.', question:'Você precisa da ergonomia do bundler ou da liberdade da plataforma?', diagram:'native' },
  { number:'05', label:'ANDAR 5 · WEB COMPONENTS', title:'Web Components: um cômodo agnóstico', intro:'Custom Elements e Shadow DOM formam um contrato nativo. O mesmo elemento pode ser consumido por Angular, React, Vue ou HTML.', bullets:['Shadow DOM reduz vazamento de CSS.','Inputs viram propriedades/atributos; outputs viram CustomEvents.','Acessibilidade, SSR, tipagem e hidratação exigem trabalho explícito.'], example:'Angular Elements publica `<checkout-summary>`; o host escuta `orderSubmitted`.', impact:'Isolamento e longevidade; possível duplicação de runtime e integração menos idiomática.', question:'O componente precisa sobreviver a vários frameworks?', diagram:'wc' },
  { number:'06', label:'ANDAR 6 · COMUNICAÇÃO', title:'Portas, não túneis secretos', intro:'Complexidade nasce de dependência e obscuridade. Comunicação deve usar contratos claros, nunca acesso direto ao store, DOM ou implementação de outro MFE.', bullets:['Inputs: estado mínimo e serializável.','Outputs: eventos de negócio, não cliques de botão.','Backend/BFF coordena dados compartilhados; URL pode ser contrato de navegação.'], example:'`<mfe-cart [items]="items" (checkoutRequested)="goToCheckout($event)">`.', impact:'Contratos estáveis permitem evolução; eventos genéricos demais criam ambiguidade.', question:'Este evento descreve negócio ou apenas revela como o botão funciona?', diagram:'communication' },
  { number:'07', label:'ANDAR 7 · IDENTIDADE', title:'Uma portaria, várias permissões', intro:'Autenticação é transversal; autorização pertence ao domínio. O usuário entra uma vez, e cada backend decide o que ele pode fazer.', bullets:['Shell/BFF coordena sessão com cookie HttpOnly, Secure e SameSite adequado.','Não grave tokens em localStorage nem duplique login em cada MFE.','Claims ajudam a UX; autorização real acontece no servidor.','Logout, expiração, refresh e cross-origin precisam de contrato.'], example:'Angular usa um AuthFacade para estado visual; APIs validam sessão e permissões por request.', impact:'SSO consistente e menor superfície de ataque; exige CORS, cookies e claims bem governados.', question:'Quem controla a chave da portaria e quem autoriza a entrada em cada andar?', diagram:'auth' },
  { number:'08', label:'ANDAR 8 · QUALIDADE', title:'O prédio precisa ser habitável', intro:'Arquitetura distribuída não pode virar desculpa para UX inconsistente. Design System, acessibilidade, responsividade e CSS isolado são contratos de qualidade.', bullets:['Tokens e componentes acessíveis devem ter ownership e semver.','Use foco visível, semântica, teclado, labels e reduced motion.','Mobile-first: não carregue MFE pesado antes da intenção do usuário.','Shadow DOM, CSS Modules ou namespaces reduzem vazamento; reset global é perigoso.'], example:'Angular CDK + tokens compartilhados; cada MFE testa teclado, leitores de tela e 320px.', impact:'Consistência e inclusão; mais governança e testes de integração visual.', question:'Um usuário de teclado encontra as mesmas portas que um usuário de mouse?', diagram:'quality' },
  { number:'09', label:'ANDAR 9 · PERFORMANCE', title:'Não construa um arranha-céu lento', intro:'Cada MFE pode trazer JS, requests e fontes. No mobile, rede e CPU tornam o custo de composição visível.', bullets:['Lazy load por rota e intenção; preload apenas o próximo passo provável.','Evite duplicar Angular, libs e polyfills; monitore bundle e long tasks.','Cache immutable para remotes versionados, fallback e timeout para falhas.','Meça LCP, INP, TTI, bytes JS e requests por jornada real.'], example:'Catálogo carrega primeiro; Checkout só baixa seu chunk após “comprar”.', impact:'Mais MFEs podem melhorar cache, mas também piorar waterfall e INP se mal compostos.', question:'Qual MFE o usuário realmente precisa pagar antes do primeiro pixel?', diagram:'performance' },
  { number:'10', label:'COBERTURA · DECISÃO', title:'Prédio concluído. Agora opere.', intro:'MFE é uma decisão organizacional e técnica. Escolha composição e tecnologia pelo domínio, pela equipe, pela experiência e pelo custo operacional.', bullets:['Module Federation: integração profunda, shared e runtime no mesmo ecossistema.','Native Federation: ESM/import maps e menor dependência de bundler.','Web Components: contrato de plataforma e isolamento entre frameworks.','Se os times não precisam de autonomia, um monólito modular pode ser melhor.'], example:'Checklist: ownership, contrato, autenticação, fallback, acessibilidade, performance e observabilidade.', impact:'O sucesso é entregar valor com limites claros — não maximizar o número de MFEs.', question:'Esta divisão reduz complexidade ou apenas distribui o monólito?', diagram:'final' },
]

function Diagram({ kind, built }: { kind:string; built:number }) { return <div className={`diagram ${kind}`}><div className="building"><div className="roof">MFE TOWER</div>{floors.slice(0,built+1).map(f=><div className="built" key={f.number}><b>{f.number}</b><span>{f.label.split(' · ')[0]}</span><i>✓</i></div>)}<div className="foundation">CONTRATOS · OBSERVABILIDADE · FALLBACK</div></div><div className="schematic">{kind==='mf'&&'HOST → REMOTES → SHARED'}{kind==='native'&&'MANIFEST → IMPORT MAP → ESM'}{kind==='wc'&&'<custom-element> · SHADOW DOM'}{kind==='auth'&&'SESSION → AUTHN → AUTHZ'}{kind==='communication'&&'INPUTS ↓ · OUTPUTS ↑'}{kind==='performance'&&'LAZY → CACHE → MEASURE'}{kind==='composition'&&'BUILD · SERVER · RUNTIME'}{kind==='quality'&&'A11Y · RESPONSIVE · CSS'}{kind==='domains'&&'CATÁLOGO | CHECKOUT | CONTA'}{kind==='tower'&&'FUNDAÇÃO'}{kind==='final'&&'STATUS: ESTÁVEL'}</div></div> }

export default function Page(){const [current,setCurrent]=useState(0); const f=floors[current]; return <main className="workshop-shell"><header className="topbar"><div className="brand-mark">MFE<span>／</span>LAB</div><div className="session-label">WORKSHOP DE ARQUITETURA <span>● AO VIVO</span></div><div className="step-count">{f.number} <span>/ 10</span></div></header><div className="layout"><nav className="floor-nav" aria-label="Etapas do workshop"><p>PLANTA VERTICAL</p>{floors.map((x,i)=><button key={x.number} className={i===current?'selected':''} aria-current={i===current?'step':undefined} onClick={()=>setCurrent(i)}><span>{x.number}</span>{x.label}</button>)}</nav><section className="content-grid"><article className="narrative"><p className="eyebrow">{f.label}</p><h1>{f.title}</h1><p className="lead">{f.intro}</p><ul>{f.bullets.map(b=><li key={b}>{b}</li>)}</ul><div className="example"><span>EXEMPLO PRÁTICO</span><p>{f.example}</p></div><div className="decision"><span>IMPACTO DA DECISÃO</span><p>{f.impact}</p></div><div className="question"><span>PAUSA PARA A SALA</span><p>{f.question}</p></div><div className="nav-actions"><button className="back" disabled={!current} onClick={()=>setCurrent(current-1)}>← voltar</button><button className="next" onClick={()=>setCurrent(current===floors.length-1?0:current+1)}>{current===floors.length-1?'recomeçar':'subir um andar'} <span>↑</span></button></div></article><aside className="blueprint-panel"><div className="panel-top"><span>PLANTA / {f.number}</span><span>{current===floors.length-1?'PRÉDIO ESTÁVEL':'OBRA EM ANDAMENTO'}</span></div><Diagram kind={f.diagram} built={current}/><div className="panel-caption"><span>ANDAR {current+1} DE {floors.length}</span><span>DECISÃO → CONSEQUÊNCIA → CONTRATO</span></div></aside></section></div><footer className="footer-note"><span>ARQUITETURA MODULAR PARA PRODUTOS QUE CRESCEM</span><span>ANGULAR 21 · MFE · WEB PLATFORM</span></footer></main>}
